### ISSUE TITLE
Check for structs/functions in other files

### ISSUE THREAD

**Issue by matteoturini** [vlang/vls#49] opened 2021-01-01 20:25 UTC

**Comment by nedpals** [comment] 2021-01-01 23:39
Closed. Duplicate of #11.

**Comment by nedpals** [comment] 2021-01-02 06:19
Sorry bout that. Will add support for checking symbols in other (unopened) files

**Comment by matteoturini** [comment] 2021-01-02 15:55
Oh, so it checks on opened files?

**Comment by nedpals** [comment] 2021-01-02 23:36
Yes.

**Comment by matteoturini** [comment] 2021-01-31 21:14
Is this feature near implementation? Any updates?

**Comment by nedpals** [comment] 2021-02-01 02:14
@matteoturini Yes and I forgot to close this. It is fixed in https://github.com/vlang/vls/commit/9bbad7d39a49e26b55d6249c7a2e6155b87ae162

**Closed by nedpals** 2021-02-01 02:14 UTC
