### ISSUE TITLE
Warns and errors in unsaved files

### ISSUE THREAD

**Issue by Sarctiann** [vlang/vls#325] opened 2022-04-25 12:50 UTC
I can write 
* wrong code 
* declare unused vars
* forget to pass arguments...
## and not know them until i save file changes

In other words, analyzer seems to be lazy while editing.

**Comment by nedpals** [comment] 2022-07-06 00:59
Closed. Duplicate of #204.

**Closed by nedpals** 2022-07-06 00:59 UTC
Labels: bug
