### ISSUE TITLE
cannot get VLS to work

### ISSUE THREAD

**Issue by despiegk** [vlang/vls#158] opened 2021-08-09 06:28 UTC
see https://docs.google.com/document/d/1Y56KDf2kfA6utKZkVeSgHBypbOlrQrjwMi77pcSjtbw/edit?usp=sharing
there is a full blown gitpod env to let you easily reproduce

**Comment by nedpals** [comment] 2021-08-09 07:58
@despiegk  Hi. I have reproduced what you've experiencing and it turns out that it's an issue when compiling it with TCC. I recommend using GCC (with `-cc gcc`) or other C compilers for now.

**Comment by nedpals** [comment] 2021-09-06 11:12
Hi, apologies for not making an update for closing this issue. This issue has already been fixed few weeks ago which has been demonstrated in this GitPod recording:

https://user-images.githubusercontent.com/7358345/132208305-2aefe461-6534-4384-a2a5-b385d1a2b0b7.mp4

The case has been the same in the latest version:

https://user-images.githubusercontent.com/7358345/132208600-f53a2919-6263-4f0f-bae0-a073639a489e.mov

Hope it clarifies the current situation about it.

**Closed by nedpals** 2021-09-06 11:12 UTC
